import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";

import { collectLiveDashboard } from "@/lib/github";
import { resolveRange } from "@/lib/range";
import { loadRoster } from "@/lib/roster";
import type { DashboardData, DashboardPreset } from "@/lib/types";

const PRESETS: DashboardPreset[] = ["7d", "30d", "90d"];

function getTokenOrThrow() {
  const token = process.env.GITHUB_TOKEN;
  if (!token) {
    throw new Error("Missing GITHUB_TOKEN for snapshot generation.");
  }

  return token;
}

function normalizeForStaticHosting(data: DashboardData): DashboardData {
  return {
    ...data,
    auth: {
      hasToken: false,
      connectionStatus: "configured",
      message: "Snapshot generated by GitHub Actions. No token is available in the browser.",
      checkedAt: data.generatedAt,
    },
    syncHealth: {
      ...data.syncHealth,
      source: "cache",
      liveEnabled: false,
    },
  };
}

async function writeSnapshotFile(filePath: string, data: unknown) {
  await mkdir(path.dirname(filePath), { recursive: true });
  await writeFile(filePath, JSON.stringify(data, null, 2), "utf8");
}

async function main() {
  const token = getTokenOrThrow();
  const roster = await loadRoster();
  const outDir = path.join(process.cwd(), "public", "snapshots");

  const generatedAt = new Date().toISOString();
  const meta: {
    generatedAt: string;
    presets: Array<{ preset: DashboardPreset; path: string; label: string }>;
  } = {
    generatedAt,
    presets: [],
  };

  for (const preset of PRESETS) {
    const range = resolveRange(preset);
    const live = await collectLiveDashboard(roster, range, token);
    const snapshot = normalizeForStaticHosting(live);

    const fileName = `${preset}.json`;
    await writeSnapshotFile(path.join(outDir, fileName), snapshot);

    meta.presets.push({ preset, path: `/snapshots/${fileName}`, label: range.label });
  }

  await writeSnapshotFile(path.join(outDir, "meta.json"), meta);
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
